# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
#  name: Default
#   name: 'Hosted Windows 2019 with VS2019'
    name: 'navbpool'
# from Azure VM
#  demands:
#    - msbuild
#    - visualstudio
#    - vstest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: 'FastTestProject/TestProject/TestProject.sln'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*TestProject*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
  continueOnError: true
  enabled: false

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/ResultsFileSamples/VsTsResults/*.trx'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/ResultsFileSamples/VsTsResults/*.trx'
  continueOnError: true
  enabled: true
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
